// AUTO-GENERATED by scripts/gen_face_catalog.mjs
// 来源：deobfuscated/face/**/*.as 的头部注释 + 正文 UI 元素解析（尺寸/背景资源/文本条/资源名/交互）。
// 供面板按 cls/group 匹配其 UI 皮肤(face)，在结构视图中渲染真实 UI 层。
export const FACE_CATALOG = [
  {
    "key": "actionface",
    "title": "ActionFace",
    "cls": "ActionFace",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/ActionFace.as",
    "sys": "表情/头像/动作浮标（face）系统 —— 屏幕右上角浮动“动作图标”队列",
    "desc": "管理界面右上角(430,85)的一排动作浮标图标（如活动推送、充值入口等），\n支持按 data.id 去重、按 data.priority 优先级增删（最多 5 个），点击触发对应服务器协议/面板。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "ActionFace",
      "Sprite"
    ]
  },
  {
    "key": "addpointface",
    "title": "AddpointFace",
    "cls": "AddpointFace",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/AddpointFace.as",
    "sys": "表情/头像（face）系统 —— 新手指引/帮助“引导点”浮标",
    "desc": "在屏幕(750,250)播放一个闪烁的指引点（point.swf 特效），点击后按 dlgType 引导玩家打开对应面板/定位光标/弹提示；\n支持多条消息排队（messageList），按 helpType 去重。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "AddpointFace",
      "Sprite"
    ]
  },
  {
    "key": "battlelistface",
    "title": "BattleListFace",
    "cls": "BattleListFace",
    "parent": "FaceSprite02",
    "pkg": "face",
    "file": "deobfuscated/face/BattleListFace.as",
    "sys": "表情/头像（face）系统 —— Boss 战实时战况悬浮条",
    "desc": "世界 Boss/团体战中右下角悬浮显示：Boss 名称与血量、参战玩家数/总伤害、伤害排行榜（前3名彩色）；\nBoss 血量支持按 time 做逐帧滚动掉血动画（定时器驱动）。",
    "size": null,
    "bg": "",
    "texts": 5,
    "resources": [],
    "interactive": false,
    "inherits": [
      "BattleListFace",
      "FaceSprite02",
      "Sprite"
    ]
  },
  {
    "key": "battletutor",
    "title": "BattleTutor",
    "cls": "BattleTutor",
    "parent": "Sprite",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/BattleTutor.as",
    "sys": "新手引导—战斗教学浮标(face.tutor)",
    "desc": "战斗教学引导步：在战斗界面上叠加两个箭头(左/下)并分别弹出\"技能/物品\"提示，教导玩家使用技能与物品。\n挂在 PromptFace 的两个战斗教学提示槽(setBattleTutorPrompt / setBattleTutorPrompt1)。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [
      "face_tutor_battleTutor_arrow"
    ],
    "interactive": false,
    "inherits": [
      "BattleTutor",
      "Sprite"
    ]
  },
  {
    "key": "bottomface",
    "title": "BottomFace",
    "cls": "BottomFace",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/BottomFace.as",
    "sys": "表情/头像（face）系统 —— 屏幕底部快捷功能栏",
    "desc": "游戏主界面的底部快捷栏：按布局批量创建全部功能按钮（战斗/邮件/自动战斗/组队/PK/角色/宠物/骑宠/背包/交易/技能/制造/好友/帮派/任务），\n挂充值按钮，处理频道切换、聊天发送，并按各管理器“有新消息”状态让对应按钮闪动提示(notifyPlayer)。",
    "size": null,
    "bg": "BottomFaceList",
    "texts": 0,
    "resources": [
      "BottomFaceList",
      "BottomFace_ITEM",
      "BottomFace_BATTLE_MACHINE",
      "face_b14",
      "BottomFace_MAIL",
      "face_b12",
      "BottomFace_AUTO_BATTLE",
      "face_b0",
      "BottomFace_TEAM_RAID",
      "face_b13",
      "BottomFace_TEAM",
      "face_b1",
      "BottomFace_PK",
      "face_b2",
      "BottomFace_PLAYER",
      "face_b3",
      "BottomFace_PET",
      "face_b4",
      "BottomFace_RIDEPET",
      "face_b15",
      "face_b5",
      "BottomFace_TRADE",
      "face_b6",
      "BottomFace_SKILL"
    ],
    "interactive": true,
    "inherits": [
      "BottomFace",
      "FaceSprite",
      "Sprite"
    ]
  },
  {
    "key": "buffsprite",
    "title": "BuffSprite",
    "cls": "BuffSprite",
    "parent": "Sprite",
    "pkg": "face.buff",
    "file": "deobfuscated/face/buff/BuffSprite.as",
    "sys": "角色 BUFF 浮层(face.buff)",
    "desc": "BUFF 图标网格容器——以 3 行×5 列(共 15 格)的 BuffSprite02 承载角色/宠物身上的 BUFF，\n提供按 BuffId 的增(addItem)/改(updateItem)/删(removeItem)及满屏清空(destoryAllItem)，并支持切换出战宠物时按归属筛选显示(showAllItem)。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "BuffSprite",
      "Sprite"
    ]
  },
  {
    "key": "buffsprite02",
    "title": "BuffSprite02",
    "cls": "BuffSprite02",
    "parent": "Sprite",
    "pkg": "face.buff",
    "file": "deobfuscated/face/buff/BuffSprite02.as",
    "sys": "角色 BUFF 浮层(face.buff，单格实现)",
    "desc": "单个 BUFF 格子——加载 32×32 图标、记录角色/宠物归属与时限(keepType/keepNum)、悬停显示提示、点击按类型(减益/增益)触发删除确认或续时面板。",
    "size": null,
    "bg": "panel_buff_bg",
    "texts": 0,
    "resources": [
      "panel_buff_bg"
    ],
    "interactive": true,
    "inherits": [
      "BuffSprite02",
      "Sprite"
    ]
  },
  {
    "key": "bugleprompt",
    "title": "BuglePrompt",
    "cls": "BuglePrompt",
    "parent": "BottomPrompt",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/BuglePrompt.as",
    "sys": "",
    "desc": "",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "BuglePrompt",
      "BottomPrompt"
    ]
  },
  {
    "key": "cityface",
    "title": "CityFace",
    "cls": "CityFace",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/CityFace.as",
    "sys": "表情/头像（face）系统 —— 屏幕左上角“城市信息/功能”浮层",
    "desc": "左上角城市信息栏：拼装城市底图、显示当前城市名、坐标(roadPoint)、网络延迟速率箭头、换线区；\n构建城市功能按钮（隐藏玩家/宝箱/地图/商城/NPC/系统/公告/换线/宠物宝箱/主题指引）并驱动公告闪动提示。",
    "size": {
      "w": 229,
      "h": 34
    },
    "bg": "face_topleft_1",
    "texts": 4,
    "resources": [
      "face_topleft_1",
      "face_topleft_2",
      "face_topleft_3",
      "face_topleft_4",
      "face_city",
      "Face_Hideplayer",
      "face_hideplayer",
      "Face_Chest",
      "face_chest",
      "Face_Map",
      "face_map",
      "Face_Mall",
      "face_shop",
      "Face_NPC",
      "face_npc",
      "Face_System",
      "face_system",
      "Face_Board",
      "face_board",
      "Face_Line",
      "face_lineframe",
      "Face_Petchest",
      "face_pet_chest",
      "Face_Guide"
    ],
    "interactive": true,
    "inherits": [
      "CityFace",
      "FaceSprite",
      "Sprite"
    ]
  },
  {
    "key": "citynameface",
    "title": "CityNameFace",
    "cls": "CityNameFace",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/CityNameFace.as",
    "sys": "表情/头像（face）系统 —— 屏幕顶部“城市名”横幅",
    "desc": "进入城市时在屏幕顶部居中显示城市名（黄字+Glow），并启动 8 秒定时器自动消失。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": true,
    "inherits": [
      "CityNameFace",
      "FaceSprite",
      "Sprite"
    ]
  },
  {
    "key": "commoninfoface",
    "title": "CommonInfoFace",
    "cls": "CommonInfoFace",
    "parent": "FaceSprite02",
    "pkg": "face",
    "file": "deobfuscated/face/CommonInfoFace.as",
    "sys": "表情/头像（face）系统 —— 通用信息悬浮提示条",
    "desc": "可拖拽的通用信息浮层（继承 FaceSprite02）：显示一段可换行 HTML 信息文本，并按内容高度自适应尺寸。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": false,
    "inherits": [
      "CommonInfoFace",
      "FaceSprite02",
      "Sprite"
    ]
  },
  {
    "key": "currentmessage",
    "title": "CurrentMessage",
    "cls": "",
    "parent": "",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/CurrentMessage.as",
    "sys": "底部提示(face.prompt)",
    "desc": "当前滚动提示消息的契约接口。统一描述一条底部广播/提示消息的剩余时间、内容、是否贴底、\n关联显示对象、所属 NPC，以及刷新(renew)与提交按钮类型。各提示实现类(CurrentMessage02 等)据此承载具体消息。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": []
  },
  {
    "key": "currentmessage02",
    "title": "CurrentMessage02",
    "cls": "CurrentMessage02",
    "parent": "PromptClass03",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/CurrentMessage02.as",
    "sys": "底部提示(face.prompt)",
    "desc": "具体消息载体——继承 PromptClass03 实现 CurrentMessage 接口，封装一条底部广播/提示消息。\n构造时固定默认显示时长 _restTime=_defaultTime=15000ms(15 秒)，供 BuglePrompt 等按秒倒计时隐藏。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "CurrentMessage02",
      "PromptClass03"
    ]
  },
  {
    "key": "divtaskface",
    "title": "DivTaskFace",
    "cls": "DivTaskFace",
    "parent": "TaskFace",
    "pkg": "face",
    "file": "deobfuscated/face/DivTaskFace.as",
    "sys": "表情/头像（face）系统 —— “灵签镇魔”分支任务浮层",
    "desc": "屏幕左侧(20,210)可拖拽的分支任务提示浮层（继承 TaskFace）：以 contentDict(键=text3)维护多条“灵签镇魔”任务文本，\n内容为空时自动从 faceLayer 移除隐藏。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "DivTaskFace",
      "TaskFace",
      "FaceSprite02",
      "Sprite"
    ]
  },
  {
    "key": "exitwatchbattleface",
    "title": "ExitWatchBattleFace",
    "cls": "ExitWatchBattleFace",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/ExitWatchBattleFace.as",
    "sys": "表情/头像（face）系统 —— 观战“退出观战”按钮",
    "desc": "观战模式下屏幕右下角(730,505)的“退出观战”按钮：点击发送 sendExitWatchBattle 退出观战；悬停高亮。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [
      "panel_exitBattleWatch"
    ],
    "interactive": true,
    "inherits": [
      "ExitWatchBattleFace",
      "Sprite"
    ]
  },
  {
    "key": "facehandler",
    "title": "FaceHandler",
    "cls": "FaceHandler",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/FaceHandler.as",
    "sys": "表情/头像（face）系统 —— 头像浮层（头顶信息条）基类",
    "desc": "玩家/宠物/他人角色“头顶信息条”的通用基类：装配头像、名字、等级、HP/MP/SP/EXP 四条状态条与 buff 区，\n处理头像点击（开角色/宠物面板、查他人信息）、各状态条悬停提示（RIGHT_CLICK_HEAD 复活指向）。",
    "size": null,
    "bg": "face_portrait_bg",
    "texts": 6,
    "resources": [
      "face_portrait_bg",
      "pet_default",
      "face_name_bg",
      "face_level_bg",
      "face_np_bg",
      "face_hp",
      "face_mp",
      "face_sp",
      "face_exp"
    ],
    "interactive": true,
    "inherits": [
      "FaceHandler",
      "FaceSprite",
      "Sprite"
    ]
  },
  {
    "key": "facesprite",
    "title": "FaceSprite",
    "cls": "FaceSprite",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/FaceSprite.as",
    "sys": "表情/头像/浮层（face）系统 —— 浮层面板基类",
    "desc": "face 模块浮层（头像/小面板）的通用基类，提供“打开/关闭/背景装配/互斥锁登记”骨架：\n构造即挂到 gameWorld.faceLayer，open/close 维护 status 并在 faceManager 登记/注销（_isForLock 控制互斥）。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "FaceSprite",
      "Sprite"
    ]
  },
  {
    "key": "facesprite02",
    "title": "FaceSprite02",
    "cls": "FaceSprite02",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/FaceSprite02.as",
    "sys": "表情/头像/浮层（face）系统 —— 可拖拽右下角悬浮提示条基类",
    "desc": "face 模块中“可拖动/可点击”悬浮小面板的通用基类（默认右下角 800-宽-40,260，宽220高60）：\n提供背景层 backSprite + 内容层 showSprite、鼠标移入高亮、拖拽到 panelLayer、点击寻路移动、内部定时器。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "FaceSprite02",
      "Sprite"
    ]
  },
  {
    "key": "facetutor",
    "title": "FaceTutor",
    "cls": "FaceTutor",
    "parent": "Sprite",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/FaceTutor.as",
    "sys": "新手引导主控(face.tutor)",
    "desc": "新手引导(欢迎/战斗教学/任务)的总控：持有提示框(faceTutorPrompt)、底部提示(hint)、模拟鼠标指针(mousePointer)、\n取消按钮(cancelBut)，并按步骤名切换当前引导步(_currentStep: StepWelcomeToTutor02)；提供遮罩镂空(drawHollow)、\n提示/指针显隐、寻路到 NPC 等能力供各步骤调用。",
    "size": null,
    "bg": "panel_btn_bg",
    "texts": 0,
    "resources": [
      "panel_btn_bg",
      "text_face_tutor",
      "face_tutor_pointer"
    ],
    "interactive": false,
    "inherits": [
      "FaceTutor",
      "Sprite"
    ]
  },
  {
    "key": "facetutorprompt",
    "title": "FaceTutorPrompt",
    "cls": "FaceTutorPrompt",
    "parent": "Sprite",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/FaceTutorPrompt.as",
    "sys": "新手引导—引导提示框(face.tutor)",
    "desc": "新手引导用的居中提示框：左侧放引导员形象图(tutor)，右侧放可自动换行/自适应的多行文案(textField)，\n底部放\"确认\"按钮(comfirmBut，派发 EVENT_COMFIRM 事件)；背景随文案尺寸自适应绘制圆角半透明框。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [
      "panel_btn_bg4",
      "text_panel_confirm2",
      "face_tutor_tutor"
    ],
    "interactive": false,
    "inherits": [
      "FaceTutorPrompt",
      "Sprite"
    ]
  },
  {
    "key": "flowersface",
    "title": "FlowersFace",
    "cls": "FlowersFace",
    "parent": "FaceSprite02",
    "pkg": "face",
    "file": "deobfuscated/face/FlowersFace.as",
    "sys": "表情/头像（face）系统 —— 送花活动实时战况悬浮条",
    "desc": "送花活动中右下角悬浮显示：当前参与人数、自己已送花朵数、送花排行榜（前3名彩色）；与 BattleListFace 同构（继承 FaceSprite02）。",
    "size": null,
    "bg": "",
    "texts": 4,
    "resources": [],
    "interactive": false,
    "inherits": [
      "FlowersFace",
      "FaceSprite02",
      "Sprite"
    ]
  },
  {
    "key": "giftface",
    "title": "GiftFace",
    "cls": "GiftFace",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/GiftFace.as",
    "sys": "表情/头像（face）系统 —— 在线奖励“礼物”浮标",
    "desc": "在线奖励礼物浮标：显示礼物图标（有礼=hasGift / 无礼=noGift）与倒计时文本；点击领取(status==1)发送 sendReceiveGift；\n倒计时归零切换为“可领取”状态，并与 phoneFace 协调屏幕位置。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": true,
    "inherits": [
      "GiftFace",
      "Sprite"
    ]
  },
  {
    "key": "groupface",
    "title": "GroupFace",
    "cls": "GroupFace",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/GroupFace.as",
    "sys": "表情/头像（face）系统 —— 队伍成员头像条",
    "desc": "屏幕右侧(x≈479)显示当前队伍 5 个成员头像槽，悬停弹出成员信息（名称/等级/职业，队长标记），含强制 PK 标记；\n数据来自 groupManager.getGroupList()。",
    "size": null,
    "bg": "face_portrait_bg",
    "texts": 0,
    "resources": [
      "face_portrait_bg",
      "face_force_pk"
    ],
    "interactive": true,
    "inherits": [
      "GroupFace",
      "Sprite"
    ]
  },
  {
    "key": "instance",
    "title": "Instance",
    "cls": "Instance",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/Instance.as",
    "sys": "表情/头像（face）系统 —— 天气/雨效播放单例",
    "desc": "全屏天气特效（雨/雪等）播放器：单例管理一组 MovieClip 雨滴，按区域随机生成、逐帧/隔帧播放并在结束后随机重定位；\n支持加载天气 SWF 资源（缓存于 GlobalsLoader.weatherEffDictionary）。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "Instance",
      "Sprite"
    ]
  },
  {
    "key": "messageface",
    "title": "MessageFace",
    "cls": "MessageFace",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/MessageFace.as",
    "sys": "表情/头像（face）系统 —— 屏幕右侧聊天/系统消息面板",
    "desc": "游戏主界面右侧(800,0)的消息面板：上方系统公告区(systemArea)、下方聊天区(chatArea)、频道切换标签(chatTab)、版本号；\n聊天超链接（玩家名/公告/FAQ）点击弹出对该玩家的操作小面板（私聊/加友/拉黑/举报），未读频道红点闪烁。",
    "size": {
      "w": 205,
      "h": 600
    },
    "bg": "face_message_bg",
    "texts": 1,
    "resources": [
      "face_message_bg",
      "panel_channel_textbg",
      "text_panel_close",
      "text_panel_accusation",
      "text_panel_private",
      "text_panel_friend",
      "text_panel_black",
      "face_message_no_select",
      "face_message_select",
      "text_face_channels_all",
      "text_face_channel1",
      "text_face_channel4",
      "text_face_channel8",
      "text_face_channel16",
      "text_face_channel32",
      "text_face_channelall",
      "text_face_channel",
      "text_face_channels_",
      "face_message_border",
      "text_face_system",
      "text_face_chat",
      "face_message_shineframe"
    ],
    "interactive": true,
    "inherits": [
      "MessageFace",
      "FaceSprite",
      "Sprite"
    ]
  },
  {
    "key": "otherplayerface",
    "title": "OtherPlayerFace",
    "cls": "OtherPlayerFace",
    "parent": "FaceHandler",
    "pkg": "face.otherplayer",
    "file": "deobfuscated/face/otherplayer/OtherPlayerFace.as",
    "sys": "表情/头像（face）系统 —— 他人角色头像浮层（含右键操作菜单）",
    "desc": "他人角色头像浮层：仅保留头像/等级/名字（移除 HP/MP/EXP/SP 条），点击弹出操作菜单（查看/宠物/观战/加友/私聊/强制PK/组队/扔物品/称号/关闭），\n各菜单项向服务器发送对应协议。",
    "size": {
      "w": 148,
      "h": 83
    },
    "bg": "face_portrait_bg",
    "texts": 0,
    "resources": [
      "face_portrait_bg",
      "face_force_pk"
    ],
    "interactive": true,
    "inherits": [
      "OtherPlayerFace",
      "FaceHandler",
      "FaceSprite",
      "Sprite"
    ]
  },
  {
    "key": "oweraction",
    "title": "OwerAction",
    "cls": "OwerAction",
    "parent": "Sprite",
    "pkg": "face.actions",
    "file": "deobfuscated/face/actions/OwerAction.as",
    "sys": "右上角\"我的动作\"浮标(face.actions，农场/家园系统动作入口)",
    "desc": "表现\"我的动作\"浮标中的单个动作图标单元——加载头像图并维护两条倒计时(开启倒计时 time / 关闭倒计时 closeTime)，\n倒计时归零分别启用交互(已开启+红光)与触发关闭回调(closeFun)，文本背景随尺寸自适应重绘。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": false,
    "inherits": [
      "OwerAction",
      "Sprite"
    ]
  },
  {
    "key": "parentpanel",
    "title": "ParentPanel",
    "cls": "",
    "parent": "",
    "pkg": "face.shortcut",
    "file": "deobfuscated/face/shortcut/ParentPanel.as",
    "sys": "快捷键栏(face.shortcut)",
    "desc": "快捷键栏/物品面板统一契约接口。约定持有者(ShortCutFace、AutoBattleItemPanel 等)需提供：\n容器(countainer)、物品层(itemLayer)、当前选中索引(currentItemIndex)的读写，以及移除选中边框(removeBorder)。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": []
  },
  {
    "key": "petface",
    "title": "PetFace",
    "cls": "PetFace",
    "parent": "FaceHandler",
    "pkg": "face",
    "file": "deobfuscated/face/PetFace.as",
    "sys": "表情/头像（face）系统 —— 宠物头像浮层",
    "desc": "宠物头像浮层（继承 FaceHandler）：宽高 148x73，默认用宠物默认头像，_type=RESUME_PET；重写 EXP/SP 条布局（宠物无 SP 条），\n并实现 HP/MP/EXP 文本与遮罩的具体绘制（按当前/最大值比例裁剪遮罩宽度）。",
    "size": {
      "w": 148,
      "h": 73
    },
    "bg": "face_portrait_bg",
    "texts": 0,
    "resources": [
      "face_portrait_bg"
    ],
    "interactive": false,
    "inherits": [
      "PetFace",
      "FaceHandler",
      "FaceSprite",
      "Sprite"
    ]
  },
  {
    "key": "phoneface",
    "title": "PhoneFace",
    "cls": "PhoneFace",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/PhoneFace.as",
    "sys": "表情/头像（face）系统 —— “手机绑定”奖励浮标",
    "desc": "手机绑定奖励浮标：播放 phoneBing.swf 特效图标，点击上报绑定(sendClient)，与 GiftFace 协调屏幕水平位置(setFaceXY)。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "PhoneFace",
      "Sprite"
    ]
  },
  {
    "key": "playerface",
    "title": "PlayerFace",
    "cls": "PlayerFace",
    "parent": "FaceHandler",
    "pkg": "face",
    "file": "deobfuscated/face/PlayerFace.as",
    "sys": "表情/头像（face）系统 —— 玩家自身头像浮层",
    "desc": "玩家自身头像浮层（继承 FaceHandler）：宽 148 高 83，贴右侧屏幕；_type=RESUME_PLAYER；\n实现 HP/MP/SP/EXP 四条状态条的具体文本与遮罩绘制（按当前/最大值比例裁剪遮罩宽度），\n并提供\"隐藏/显示套装\"切换条（点击向服务器发送 sendSuitShowMSG）。",
    "size": {
      "w": 148,
      "h": 83
    },
    "bg": "face_portrait_bg",
    "texts": 1,
    "resources": [
      "face_portrait_bg",
      "face_force_pk"
    ],
    "interactive": true,
    "inherits": [
      "PlayerFace",
      "FaceHandler",
      "FaceSprite",
      "Sprite"
    ]
  },
  {
    "key": "promptclass",
    "title": "PromptClass",
    "cls": "PromptClass",
    "parent": "BottomPrompt",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/PromptClass.as",
    "sys": "底部提示(face.prompt)",
    "desc": "带可视背景的底部提示消息(继承 BottomPrompt 并满足 CurrentMessage 契约)。默认显示 6 秒。\n自身即显示对象(displayObject=this)，可在 set content 时通过 setChatText 渲染为聊天样式文本(宽 156)。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "PromptClass",
      "BottomPrompt"
    ]
  },
  {
    "key": "promptclass02",
    "title": "PromptClass02",
    "cls": "PromptClass02",
    "parent": "PromptClass03",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/PromptClass02.as",
    "sys": "底部提示(face.prompt)",
    "desc": "红色强调型提示消息(继承 PromptClass03)。构造时把正文包裹为红色字体(<font color='#FF0000'>)，\n默认显示时长 15 秒(较基类更长)，用于错误/警告/重要广播。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "PromptClass02",
      "PromptClass03"
    ]
  },
  {
    "key": "promptclass03",
    "title": "PromptClass03",
    "cls": "PromptClass03",
    "parent": "",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/PromptClass03.as",
    "sys": "底部提示(face.prompt)",
    "desc": "当前消息的基类实现(CurrentMessage)。持有内容(_content)、剩余时间(_restTime)与默认时长(_defaultTime)、是否贴底(_bottom)。\n提供通用的 getter/setter 与 renew(重置剩余时间为默认)。子类 CurrentMessage02/PromptClass02/04 仅调整默认时长与内容样式。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "PromptClass03"
    ]
  },
  {
    "key": "promptclass04",
    "title": "PromptClass04",
    "cls": "PromptClass04",
    "parent": "PromptClass03",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/PromptClass04.as",
    "sys": "底部提示(face.prompt)",
    "desc": "普通提示消息(继承 PromptClass03)。与基类默认时长一致，默认显示 10 秒，正文不附加颜色样式。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "PromptClass04",
      "PromptClass03"
    ]
  },
  {
    "key": "promptface",
    "title": "PromptFace",
    "cls": "PromptFace",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/PromptFace.as",
    "sys": "提示系统(face) —— 屏幕各类悬浮提示/气泡的总管",
    "desc": "汇总并管理所有屏幕提示浮层：顶部滚动消息(topPrompt)、大喇叭(_buglePrompt)、底部系统提示(_bottomPrompt)、\n跟随鼠标的信息提示(infoPrompt)、装备对比提示(contrastList)、当前发言气泡(_privateChatPrompt/_chatPromptArray)、\n自动挂机图标(autoFountImg)、战斗教学提示(_battleTutorPrompt/1)、当前线提示(_nowLinePrompt)，并驱动聊天气泡计时收起。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [
      "state_autofount"
    ],
    "interactive": true,
    "inherits": [
      "PromptFace",
      "Sprite"
    ]
  },
  {
    "key": "promptprogress",
    "title": "PromptProgress",
    "cls": "PromptProgress",
    "parent": "SendPanel",
    "pkg": "face",
    "file": "deobfuscated/face/PromptProgress.as",
    "sys": "采集/生活技能进度提示(face)",
    "desc": "屏幕上的采集(生活技能)进度面板。显示\"采集中/等待\"标题，进度条按服务器节拍刷新百分比，点击可取消；\n进度条悬停时弹出采集提示(infoPrompt)。复用 SendPanel 的基础进度条与面板结构。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "PromptProgress",
      "SendPanel"
    ]
  },
  {
    "key": "raceface",
    "title": "RaceFace",
    "cls": "RaceFace",
    "parent": "Sprite",
    "pkg": "face.match",
    "file": "deobfuscated/face/match/RaceFace.as",
    "sys": "赛事/匹配浮层(face.match)",
    "desc": "赛事报名/排队等待浮标——显示自由赛排队人数或公会赛 1 秒倒计时，提供\"离开排队\"按钮，支持拖拽与点击空白处寻路移动玩家。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [
      "panel_btn_bg1",
      "text_panel_exit_race_freedom",
      "text_panel_exit_race_guild"
    ],
    "interactive": true,
    "inherits": [
      "RaceFace",
      "Sprite"
    ]
  },
  {
    "key": "raidface",
    "title": "RaidFace",
    "cls": "RaidFace",
    "parent": "FaceSprite02",
    "pkg": "face",
    "file": "deobfuscated/face/RaidFace.as",
    "sys": "突袭/Raid 战况浮层(face)",
    "desc": "显示世界突袭(Raid)活动进度浮标：列出待击败列表(fallowList)与当前进行列表(curList)中各目标描述、剩余时间与状态\n(待战/已击败/已编成/计时中/暂停)。每拍由 timeHandler 重算刷新；可拖拽(继承 FaceSprite02)。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": false,
    "inherits": [
      "RaidFace",
      "FaceSprite02",
      "Sprite"
    ]
  },
  {
    "key": "sendmessageface",
    "title": "SendMessageFace",
    "cls": "SendMessageFace",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/SendMessageFace.as",
    "sys": "聊天输入栏(face)",
    "desc": "屏幕左下角聊天/发言输入浮层。承载输入框(chatInput，限 80 字)、表情/活动/清屏/回答/频道/颜色/侧栏开关等按钮，\n处理快捷键唤起面板、发送消息(sendChatMsg，支持\"/\"指令与链接转换)、私聊提示、侧栏收展动画(toggleSideBar)。",
    "size": {
      "w": 205,
      "h": 50
    },
    "bg": "face_message_chat",
    "texts": 1,
    "resources": [
      "face_message_chat",
      "face_channel_bg2",
      "text_face_emote",
      "text_face_active",
      "text_face_clear_text",
      "text_face_answer",
      "text_face_channels_2",
      "face_Switch",
      "text_face_channels_"
    ],
    "interactive": true,
    "inherits": [
      "SendMessageFace",
      "FaceSprite",
      "Sprite"
    ]
  },
  {
    "key": "shortcutface",
    "title": "ShortCutFace",
    "cls": "ShortCutFace",
    "parent": "FaceSprite",
    "pkg": "face.shortcut",
    "file": "deobfuscated/face/shortcut/ShortCutFace.as",
    "sys": "快捷键栏(face.shortcut)",
    "desc": "屏幕底部(426,510)的快捷键栏。共 20 个格子分\"玩家(curType=0)/宠物(curType=1)\"两组各 10 格，可切换(switchHandler)。\n每格由 ShortCutParent 承载(物品/技能图标、数量、可用置灰)；提供显示/隐藏开关(flag)、锁定(isLock)、掩膜(isMask)、选中边框、\n性能档切换(switchPerformance)。实现 ParentPanel 供 ShortCutParent 接入 itemLayer。",
    "size": null,
    "bg": "face_player_cut_lock",
    "texts": 1,
    "resources": [
      "face_player_cut_lock",
      "face_Switch",
      "face_player_cut_unlock",
      "face_PlayerShortCut",
      "face_petShortCut",
      "face_pet_cut_lock",
      "face_pet_cut_unlock",
      "item_select"
    ],
    "interactive": true,
    "inherits": [
      "ShortCutFace",
      "FaceSprite",
      "Sprite"
    ]
  },
  {
    "key": "shortcutparent",
    "title": "ShortCutParent",
    "cls": "ShortCutParent",
    "parent": "Sprite",
    "pkg": "face.shortcut",
    "file": "deobfuscated/face/shortcut/ShortCutParent.as",
    "sys": "快捷键栏(face.shortcut)，作为 ShortCutFace 中单个格子的承载组件",
    "desc": "承载一个快捷键(物品/技能)格子的图标(imgSprite)、数量(countField)、可用性置灰(canuse)、描述(desc)与提示(getInfo)。\n通过 parentPanel(ParentPanel 契约，实际为 ShortCutFace 或 AutoBattleItemPanel)挂载到图标层 itemLayer。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": true,
    "inherits": [
      "ShortCutParent",
      "Sprite"
    ]
  },
  {
    "key": "showplayerbutton",
    "title": "ShowplayerButton",
    "cls": "ShowplayerButton",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/ShowplayerButton.as",
    "sys": "浮层按钮(face)",
    "desc": "通用\"图标按钮\"浮层单元：用一张图片(_image)作背景，可指定尺寸/位置、是否参与互斥锁(_isForLock)、是否可换图(isChangeFace)。\n默认在 y=46-高度 处贴底显示；也可按 setY 用 initBackground 在指定坐标绘制。flag4=false 时置灰(disabled 态)。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "ShowplayerButton",
      "FaceSprite",
      "Sprite"
    ]
  },
  {
    "key": "sidebarface",
    "title": "SideBarFace",
    "cls": "SideBarFace",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/SideBarFace.as",
    "sys": "右侧工具栏(face)",
    "desc": "屏幕右侧竖条工具条(SideBar)：绘制圆角画布(50x520)，放置一个\"下载快捷方式\"按钮(buttonList)。\n按钮点击打开官网攻略页并(登录态)上报 sendDownloadShortcut。可被 SendMessageFace.toggleSideBar 收展(showFace/clearFace)。",
    "size": null,
    "bg": "face_side_bg",
    "texts": 0,
    "resources": [
      "face_side_bg",
      "face_download_shortcut"
    ],
    "interactive": false,
    "inherits": [
      "SideBarFace",
      "FaceSprite",
      "Sprite"
    ]
  },
  {
    "key": "steptaskcompletehint",
    "title": "StepTaskCompleteHint",
    "cls": "StepTaskCompleteHint",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepTaskCompleteHint.as",
    "sys": "新手引导—任务完成提示步(face.tutor)",
    "desc": "引导步\"任务完成提示\"：聚焦引导 NPC(_tutorNpcId=1004)，绘制镂空高亮、放置模拟鼠标、在 NPC 头顶显示提示文案，\n并监听对话面板打开(TUTOR_TALKPANEL_OPEN)以推进到\"任务完成展示(StepTaskCompleteShow)\"步。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepTaskCompleteHint"
    ]
  },
  {
    "key": "steptaskcompleteshow",
    "title": "StepTaskCompleteShow",
    "cls": "StepTaskCompleteShow",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepTaskCompleteShow.as",
    "sys": "新手引导—任务完成展示步(face.tutor)",
    "desc": "引导步\"任务完成展示\"：在固定坐标(564,265)放置模拟鼠标、在(410,267,156,16)绘制镂空高亮、在(564,330)显示提示文案，\n并监听对话面板关闭(TUTOR_TALKPANEL_CLOSE)以推进到\"任务完成提交(StepTaskCompleteSubmit)\"步。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepTaskCompleteShow"
    ]
  },
  {
    "key": "steptaskcompletesubmit",
    "title": "StepTaskCompleteSubmit",
    "cls": "StepTaskCompleteSubmit",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepTaskCompleteSubmit.as",
    "sys": "新手引导—任务完成提交步(face.tutor)",
    "desc": "引导步\"任务完成提交\"：在(445,430)放置模拟鼠标、在(361,428,82,26)绘制镂空高亮(提交按钮区)、在(445,490)显示提示文案，\n并监听对话面板关闭(TUTOR_TALKPANEL_CLOSE)以推进到末步\"最后欢迎(StepWelcomeLast)\"。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepTaskCompleteSubmit"
    ]
  },
  {
    "key": "stepwelcome",
    "title": "StepWelcome",
    "cls": "StepWelcome",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepWelcome.as",
    "sys": "新手引导—欢迎首步(face.tutor)",
    "desc": "引导流程第一步：展示欢迎提示框(faceTutorPrompt)，在确认按钮上方放置模拟鼠标，绘制全屏半透明遮罩(0.8，\n聚焦确认按钮)，上报引导步(\"welcome\")；监听确认后切到\"欢迎→引导(WELCOME_TO_TUTOR)\"步。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepWelcome"
    ]
  },
  {
    "key": "stepwelcomelast",
    "title": "StepWelcomeLast",
    "cls": "StepWelcomeLast",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepWelcomeLast.as",
    "sys": "新手引导—欢迎末步(face.tutor)",
    "desc": "引导流程最后一步：展示末步提示框(STEP_WELCOME_LAST)，在确认按钮上方放置模拟鼠标，绘制全屏半透明遮罩(0.8)，\n上报引导步(\"welcomeLast\")；确认后直接终止整个新手引导(tutorManager.stopTutor)，不再切换下一步。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepWelcomeLast"
    ]
  },
  {
    "key": "stepwelcometaskaccept",
    "title": "StepWelcomeTaskAccept",
    "cls": "StepWelcomeTaskAccept",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepWelcomeTaskAccept.as",
    "sys": "新手引导—提交欢迎任务步(face.tutor)",
    "desc": "引导步\"提交欢迎任务\"：在任务提交按钮区(390,446,80,26)绘制镂空高亮、在(470,446)放模拟鼠标、在(470,510)显示提示(STEP_WELCOME_TASK_ACCEPT)，\n并监听对话面板关闭(TUTOR_TALKPANEL_CLOSE)以推进到\"任务完成提示(TASK_COMPLETE_HINT)\"步。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepWelcomeTaskAccept"
    ]
  },
  {
    "key": "stepwelcometaskshow",
    "title": "StepWelcomeTaskShow",
    "cls": "StepWelcomeTaskShow",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepWelcomeTaskShow.as",
    "sys": "新手引导—展示欢迎任务步(face.tutor)",
    "desc": "引导步\"展示欢迎任务\"：在(530,240)放模拟鼠标、任务条目区(410,240,114,18)绘制镂空高亮、在(530,300)显示提示(STEP_WELCOME_TAKS_SHOW)，\n并监听对话面板关闭(TUTOR_TALKPANEL_CLOSE)以推进到\"提交欢迎任务(ACCEPT_WELCOME_TASK_SUBMIT)\"步。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepWelcomeTaskShow"
    ]
  },
  {
    "key": "stepwelcometotutor",
    "title": "StepWelcomeToTutor",
    "cls": "StepWelcomeToTutor",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepWelcomeToTutor.as",
    "sys": "新手引导—欢迎→引导过渡步(face.tutor)",
    "desc": "引导流程\"欢迎→引导\"过渡步：把镜头/玩家移动到引导 NPC(_tutorNpcId=1004，不触发对话)，上报引导步(\"welcomToTutor\")；\n待地图与玩家资源加载完成(onComplete)后，在 NPC 处一次性展示镂空高亮/模拟鼠标/提示；对话面板打开时切到\"展示欢迎任务\"步。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepWelcomeToTutor"
    ]
  },
  {
    "key": "stepwelcometotutor02",
    "title": "StepWelcomeToTutor02",
    "cls": "",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepWelcomeToTutor02.as",
    "sys": "新手引导—引导步骤契约接口(face.tutor)",
    "desc": "新手引导步骤的统一契约接口：所有引导步(StepWelcome / StepWelcomeToTutor / StepTaskComplete* / StepWelcomeLast 等)均需实现，\n由引导主控 FaceTutor 通过 switchStep 按步骤名切换并调用 apply() 激活、clear() 退出。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": []
  },
  {
    "key": "taskface",
    "title": "TaskFace",
    "cls": "TaskFace",
    "parent": "FaceSprite02",
    "pkg": "face",
    "file": "deobfuscated/face/TaskFace.as",
    "sys": "任务追踪浮层(face)",
    "desc": "屏幕左侧任务追踪列表(可拖拽，继承 FaceSprite02)。维护\"关注任务\"列表(taskFollowlist，最多 4 条)，\n每条约 350ms 重绘：显示标题(未完成橙/已完成紫)、剩余时间(有 times 时启动计时)、条件条目。点击任务可寻路/打开任务面板。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": true,
    "inherits": [
      "TaskFace",
      "FaceSprite02",
      "Sprite"
    ]
  },
  {
    "key": "topprompt",
    "title": "TopPrompt",
    "cls": "TopPrompt",
    "parent": "BottomPrompt",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/TopPrompt.as",
    "sys": "顶部消息滚动提示(face.prompt)",
    "desc": "顶部居中滚动广播/系统消息条。维护\"处理中列表(messageProcessList,最多3条)\"与\"缓冲列表(messageBufferList)\"，\n每 1 秒(messageTimer)递减各消息剩余时间、移除超时、在有空位时把缓冲广播补入并刷新显示。\n支持文本超链接点击(寻路/查看)、鼠标移动联动场景光标。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": true,
    "inherits": [
      "TopPrompt",
      "BottomPrompt"
    ]
  },
  {
    "key": "topprompt02",
    "title": "TopPrompt02",
    "cls": "",
    "parent": "",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/TopPrompt02.as",
    "sys": "顶部/大喇叭提示(face.prompt)",
    "desc": "顶部滚动提示条统一契约接口，供外部(如 PromptFace)以多态方式持有并操作。约定：\naddMessage 按通道(value)追加一条消息；clear 隐藏并复位；addHttpListener 注册文本超链接回调；x/y 控制位置。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": []
  }
];
export const FACE_BY_NAME = {
  "ActionFace": {
    "key": "actionface",
    "title": "ActionFace",
    "cls": "ActionFace",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/ActionFace.as",
    "sys": "表情/头像/动作浮标（face）系统 —— 屏幕右上角浮动“动作图标”队列",
    "desc": "管理界面右上角(430,85)的一排动作浮标图标（如活动推送、充值入口等），\n支持按 data.id 去重、按 data.priority 优先级增删（最多 5 个），点击触发对应服务器协议/面板。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "ActionFace",
      "Sprite"
    ]
  },
  "AddpointFace": {
    "key": "addpointface",
    "title": "AddpointFace",
    "cls": "AddpointFace",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/AddpointFace.as",
    "sys": "表情/头像（face）系统 —— 新手指引/帮助“引导点”浮标",
    "desc": "在屏幕(750,250)播放一个闪烁的指引点（point.swf 特效），点击后按 dlgType 引导玩家打开对应面板/定位光标/弹提示；\n支持多条消息排队（messageList），按 helpType 去重。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "AddpointFace",
      "Sprite"
    ]
  },
  "BattleListFace": {
    "key": "battlelistface",
    "title": "BattleListFace",
    "cls": "BattleListFace",
    "parent": "FaceSprite02",
    "pkg": "face",
    "file": "deobfuscated/face/BattleListFace.as",
    "sys": "表情/头像（face）系统 —— Boss 战实时战况悬浮条",
    "desc": "世界 Boss/团体战中右下角悬浮显示：Boss 名称与血量、参战玩家数/总伤害、伤害排行榜（前3名彩色）；\nBoss 血量支持按 time 做逐帧滚动掉血动画（定时器驱动）。",
    "size": null,
    "bg": "",
    "texts": 5,
    "resources": [],
    "interactive": false,
    "inherits": [
      "BattleListFace",
      "FaceSprite02",
      "Sprite"
    ]
  },
  "BattleTutor": {
    "key": "battletutor",
    "title": "BattleTutor",
    "cls": "BattleTutor",
    "parent": "Sprite",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/BattleTutor.as",
    "sys": "新手引导—战斗教学浮标(face.tutor)",
    "desc": "战斗教学引导步：在战斗界面上叠加两个箭头(左/下)并分别弹出\"技能/物品\"提示，教导玩家使用技能与物品。\n挂在 PromptFace 的两个战斗教学提示槽(setBattleTutorPrompt / setBattleTutorPrompt1)。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [
      "face_tutor_battleTutor_arrow"
    ],
    "interactive": false,
    "inherits": [
      "BattleTutor",
      "Sprite"
    ]
  },
  "BottomFace": {
    "key": "bottomface",
    "title": "BottomFace",
    "cls": "BottomFace",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/BottomFace.as",
    "sys": "表情/头像（face）系统 —— 屏幕底部快捷功能栏",
    "desc": "游戏主界面的底部快捷栏：按布局批量创建全部功能按钮（战斗/邮件/自动战斗/组队/PK/角色/宠物/骑宠/背包/交易/技能/制造/好友/帮派/任务），\n挂充值按钮，处理频道切换、聊天发送，并按各管理器“有新消息”状态让对应按钮闪动提示(notifyPlayer)。",
    "size": null,
    "bg": "BottomFaceList",
    "texts": 0,
    "resources": [
      "BottomFaceList",
      "BottomFace_ITEM",
      "BottomFace_BATTLE_MACHINE",
      "face_b14",
      "BottomFace_MAIL",
      "face_b12",
      "BottomFace_AUTO_BATTLE",
      "face_b0",
      "BottomFace_TEAM_RAID",
      "face_b13",
      "BottomFace_TEAM",
      "face_b1",
      "BottomFace_PK",
      "face_b2",
      "BottomFace_PLAYER",
      "face_b3",
      "BottomFace_PET",
      "face_b4",
      "BottomFace_RIDEPET",
      "face_b15",
      "face_b5",
      "BottomFace_TRADE",
      "face_b6",
      "BottomFace_SKILL"
    ],
    "interactive": true,
    "inherits": [
      "BottomFace",
      "FaceSprite",
      "Sprite"
    ]
  },
  "BuffSprite": {
    "key": "buffsprite",
    "title": "BuffSprite",
    "cls": "BuffSprite",
    "parent": "Sprite",
    "pkg": "face.buff",
    "file": "deobfuscated/face/buff/BuffSprite.as",
    "sys": "角色 BUFF 浮层(face.buff)",
    "desc": "BUFF 图标网格容器——以 3 行×5 列(共 15 格)的 BuffSprite02 承载角色/宠物身上的 BUFF，\n提供按 BuffId 的增(addItem)/改(updateItem)/删(removeItem)及满屏清空(destoryAllItem)，并支持切换出战宠物时按归属筛选显示(showAllItem)。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "BuffSprite",
      "Sprite"
    ]
  },
  "BuffSprite02": {
    "key": "buffsprite02",
    "title": "BuffSprite02",
    "cls": "BuffSprite02",
    "parent": "Sprite",
    "pkg": "face.buff",
    "file": "deobfuscated/face/buff/BuffSprite02.as",
    "sys": "角色 BUFF 浮层(face.buff，单格实现)",
    "desc": "单个 BUFF 格子——加载 32×32 图标、记录角色/宠物归属与时限(keepType/keepNum)、悬停显示提示、点击按类型(减益/增益)触发删除确认或续时面板。",
    "size": null,
    "bg": "panel_buff_bg",
    "texts": 0,
    "resources": [
      "panel_buff_bg"
    ],
    "interactive": true,
    "inherits": [
      "BuffSprite02",
      "Sprite"
    ]
  },
  "BuglePrompt": {
    "key": "bugleprompt",
    "title": "BuglePrompt",
    "cls": "BuglePrompt",
    "parent": "BottomPrompt",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/BuglePrompt.as",
    "sys": "",
    "desc": "",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "BuglePrompt",
      "BottomPrompt"
    ]
  },
  "CityFace": {
    "key": "cityface",
    "title": "CityFace",
    "cls": "CityFace",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/CityFace.as",
    "sys": "表情/头像（face）系统 —— 屏幕左上角“城市信息/功能”浮层",
    "desc": "左上角城市信息栏：拼装城市底图、显示当前城市名、坐标(roadPoint)、网络延迟速率箭头、换线区；\n构建城市功能按钮（隐藏玩家/宝箱/地图/商城/NPC/系统/公告/换线/宠物宝箱/主题指引）并驱动公告闪动提示。",
    "size": {
      "w": 229,
      "h": 34
    },
    "bg": "face_topleft_1",
    "texts": 4,
    "resources": [
      "face_topleft_1",
      "face_topleft_2",
      "face_topleft_3",
      "face_topleft_4",
      "face_city",
      "Face_Hideplayer",
      "face_hideplayer",
      "Face_Chest",
      "face_chest",
      "Face_Map",
      "face_map",
      "Face_Mall",
      "face_shop",
      "Face_NPC",
      "face_npc",
      "Face_System",
      "face_system",
      "Face_Board",
      "face_board",
      "Face_Line",
      "face_lineframe",
      "Face_Petchest",
      "face_pet_chest",
      "Face_Guide"
    ],
    "interactive": true,
    "inherits": [
      "CityFace",
      "FaceSprite",
      "Sprite"
    ]
  },
  "CityNameFace": {
    "key": "citynameface",
    "title": "CityNameFace",
    "cls": "CityNameFace",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/CityNameFace.as",
    "sys": "表情/头像（face）系统 —— 屏幕顶部“城市名”横幅",
    "desc": "进入城市时在屏幕顶部居中显示城市名（黄字+Glow），并启动 8 秒定时器自动消失。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": true,
    "inherits": [
      "CityNameFace",
      "FaceSprite",
      "Sprite"
    ]
  },
  "CommonInfoFace": {
    "key": "commoninfoface",
    "title": "CommonInfoFace",
    "cls": "CommonInfoFace",
    "parent": "FaceSprite02",
    "pkg": "face",
    "file": "deobfuscated/face/CommonInfoFace.as",
    "sys": "表情/头像（face）系统 —— 通用信息悬浮提示条",
    "desc": "可拖拽的通用信息浮层（继承 FaceSprite02）：显示一段可换行 HTML 信息文本，并按内容高度自适应尺寸。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": false,
    "inherits": [
      "CommonInfoFace",
      "FaceSprite02",
      "Sprite"
    ]
  },
  "": {
    "key": "topprompt02",
    "title": "TopPrompt02",
    "cls": "",
    "parent": "",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/TopPrompt02.as",
    "sys": "顶部/大喇叭提示(face.prompt)",
    "desc": "顶部滚动提示条统一契约接口，供外部(如 PromptFace)以多态方式持有并操作。约定：\naddMessage 按通道(value)追加一条消息；clear 隐藏并复位；addHttpListener 注册文本超链接回调；x/y 控制位置。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": []
  },
  "CurrentMessage02": {
    "key": "currentmessage02",
    "title": "CurrentMessage02",
    "cls": "CurrentMessage02",
    "parent": "PromptClass03",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/CurrentMessage02.as",
    "sys": "底部提示(face.prompt)",
    "desc": "具体消息载体——继承 PromptClass03 实现 CurrentMessage 接口，封装一条底部广播/提示消息。\n构造时固定默认显示时长 _restTime=_defaultTime=15000ms(15 秒)，供 BuglePrompt 等按秒倒计时隐藏。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "CurrentMessage02",
      "PromptClass03"
    ]
  },
  "DivTaskFace": {
    "key": "divtaskface",
    "title": "DivTaskFace",
    "cls": "DivTaskFace",
    "parent": "TaskFace",
    "pkg": "face",
    "file": "deobfuscated/face/DivTaskFace.as",
    "sys": "表情/头像（face）系统 —— “灵签镇魔”分支任务浮层",
    "desc": "屏幕左侧(20,210)可拖拽的分支任务提示浮层（继承 TaskFace）：以 contentDict(键=text3)维护多条“灵签镇魔”任务文本，\n内容为空时自动从 faceLayer 移除隐藏。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "DivTaskFace",
      "TaskFace",
      "FaceSprite02",
      "Sprite"
    ]
  },
  "ExitWatchBattleFace": {
    "key": "exitwatchbattleface",
    "title": "ExitWatchBattleFace",
    "cls": "ExitWatchBattleFace",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/ExitWatchBattleFace.as",
    "sys": "表情/头像（face）系统 —— 观战“退出观战”按钮",
    "desc": "观战模式下屏幕右下角(730,505)的“退出观战”按钮：点击发送 sendExitWatchBattle 退出观战；悬停高亮。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [
      "panel_exitBattleWatch"
    ],
    "interactive": true,
    "inherits": [
      "ExitWatchBattleFace",
      "Sprite"
    ]
  },
  "FaceHandler": {
    "key": "facehandler",
    "title": "FaceHandler",
    "cls": "FaceHandler",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/FaceHandler.as",
    "sys": "表情/头像（face）系统 —— 头像浮层（头顶信息条）基类",
    "desc": "玩家/宠物/他人角色“头顶信息条”的通用基类：装配头像、名字、等级、HP/MP/SP/EXP 四条状态条与 buff 区，\n处理头像点击（开角色/宠物面板、查他人信息）、各状态条悬停提示（RIGHT_CLICK_HEAD 复活指向）。",
    "size": null,
    "bg": "face_portrait_bg",
    "texts": 6,
    "resources": [
      "face_portrait_bg",
      "pet_default",
      "face_name_bg",
      "face_level_bg",
      "face_np_bg",
      "face_hp",
      "face_mp",
      "face_sp",
      "face_exp"
    ],
    "interactive": true,
    "inherits": [
      "FaceHandler",
      "FaceSprite",
      "Sprite"
    ]
  },
  "FaceSprite": {
    "key": "facesprite",
    "title": "FaceSprite",
    "cls": "FaceSprite",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/FaceSprite.as",
    "sys": "表情/头像/浮层（face）系统 —— 浮层面板基类",
    "desc": "face 模块浮层（头像/小面板）的通用基类，提供“打开/关闭/背景装配/互斥锁登记”骨架：\n构造即挂到 gameWorld.faceLayer，open/close 维护 status 并在 faceManager 登记/注销（_isForLock 控制互斥）。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "FaceSprite",
      "Sprite"
    ]
  },
  "FaceSprite02": {
    "key": "facesprite02",
    "title": "FaceSprite02",
    "cls": "FaceSprite02",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/FaceSprite02.as",
    "sys": "表情/头像/浮层（face）系统 —— 可拖拽右下角悬浮提示条基类",
    "desc": "face 模块中“可拖动/可点击”悬浮小面板的通用基类（默认右下角 800-宽-40,260，宽220高60）：\n提供背景层 backSprite + 内容层 showSprite、鼠标移入高亮、拖拽到 panelLayer、点击寻路移动、内部定时器。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "FaceSprite02",
      "Sprite"
    ]
  },
  "FaceTutor": {
    "key": "facetutor",
    "title": "FaceTutor",
    "cls": "FaceTutor",
    "parent": "Sprite",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/FaceTutor.as",
    "sys": "新手引导主控(face.tutor)",
    "desc": "新手引导(欢迎/战斗教学/任务)的总控：持有提示框(faceTutorPrompt)、底部提示(hint)、模拟鼠标指针(mousePointer)、\n取消按钮(cancelBut)，并按步骤名切换当前引导步(_currentStep: StepWelcomeToTutor02)；提供遮罩镂空(drawHollow)、\n提示/指针显隐、寻路到 NPC 等能力供各步骤调用。",
    "size": null,
    "bg": "panel_btn_bg",
    "texts": 0,
    "resources": [
      "panel_btn_bg",
      "text_face_tutor",
      "face_tutor_pointer"
    ],
    "interactive": false,
    "inherits": [
      "FaceTutor",
      "Sprite"
    ]
  },
  "FaceTutorPrompt": {
    "key": "facetutorprompt",
    "title": "FaceTutorPrompt",
    "cls": "FaceTutorPrompt",
    "parent": "Sprite",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/FaceTutorPrompt.as",
    "sys": "新手引导—引导提示框(face.tutor)",
    "desc": "新手引导用的居中提示框：左侧放引导员形象图(tutor)，右侧放可自动换行/自适应的多行文案(textField)，\n底部放\"确认\"按钮(comfirmBut，派发 EVENT_COMFIRM 事件)；背景随文案尺寸自适应绘制圆角半透明框。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [
      "panel_btn_bg4",
      "text_panel_confirm2",
      "face_tutor_tutor"
    ],
    "interactive": false,
    "inherits": [
      "FaceTutorPrompt",
      "Sprite"
    ]
  },
  "FlowersFace": {
    "key": "flowersface",
    "title": "FlowersFace",
    "cls": "FlowersFace",
    "parent": "FaceSprite02",
    "pkg": "face",
    "file": "deobfuscated/face/FlowersFace.as",
    "sys": "表情/头像（face）系统 —— 送花活动实时战况悬浮条",
    "desc": "送花活动中右下角悬浮显示：当前参与人数、自己已送花朵数、送花排行榜（前3名彩色）；与 BattleListFace 同构（继承 FaceSprite02）。",
    "size": null,
    "bg": "",
    "texts": 4,
    "resources": [],
    "interactive": false,
    "inherits": [
      "FlowersFace",
      "FaceSprite02",
      "Sprite"
    ]
  },
  "GiftFace": {
    "key": "giftface",
    "title": "GiftFace",
    "cls": "GiftFace",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/GiftFace.as",
    "sys": "表情/头像（face）系统 —— 在线奖励“礼物”浮标",
    "desc": "在线奖励礼物浮标：显示礼物图标（有礼=hasGift / 无礼=noGift）与倒计时文本；点击领取(status==1)发送 sendReceiveGift；\n倒计时归零切换为“可领取”状态，并与 phoneFace 协调屏幕位置。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": true,
    "inherits": [
      "GiftFace",
      "Sprite"
    ]
  },
  "GroupFace": {
    "key": "groupface",
    "title": "GroupFace",
    "cls": "GroupFace",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/GroupFace.as",
    "sys": "表情/头像（face）系统 —— 队伍成员头像条",
    "desc": "屏幕右侧(x≈479)显示当前队伍 5 个成员头像槽，悬停弹出成员信息（名称/等级/职业，队长标记），含强制 PK 标记；\n数据来自 groupManager.getGroupList()。",
    "size": null,
    "bg": "face_portrait_bg",
    "texts": 0,
    "resources": [
      "face_portrait_bg",
      "face_force_pk"
    ],
    "interactive": true,
    "inherits": [
      "GroupFace",
      "Sprite"
    ]
  },
  "Instance": {
    "key": "instance",
    "title": "Instance",
    "cls": "Instance",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/Instance.as",
    "sys": "表情/头像（face）系统 —— 天气/雨效播放单例",
    "desc": "全屏天气特效（雨/雪等）播放器：单例管理一组 MovieClip 雨滴，按区域随机生成、逐帧/隔帧播放并在结束后随机重定位；\n支持加载天气 SWF 资源（缓存于 GlobalsLoader.weatherEffDictionary）。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "Instance",
      "Sprite"
    ]
  },
  "MessageFace": {
    "key": "messageface",
    "title": "MessageFace",
    "cls": "MessageFace",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/MessageFace.as",
    "sys": "表情/头像（face）系统 —— 屏幕右侧聊天/系统消息面板",
    "desc": "游戏主界面右侧(800,0)的消息面板：上方系统公告区(systemArea)、下方聊天区(chatArea)、频道切换标签(chatTab)、版本号；\n聊天超链接（玩家名/公告/FAQ）点击弹出对该玩家的操作小面板（私聊/加友/拉黑/举报），未读频道红点闪烁。",
    "size": {
      "w": 205,
      "h": 600
    },
    "bg": "face_message_bg",
    "texts": 1,
    "resources": [
      "face_message_bg",
      "panel_channel_textbg",
      "text_panel_close",
      "text_panel_accusation",
      "text_panel_private",
      "text_panel_friend",
      "text_panel_black",
      "face_message_no_select",
      "face_message_select",
      "text_face_channels_all",
      "text_face_channel1",
      "text_face_channel4",
      "text_face_channel8",
      "text_face_channel16",
      "text_face_channel32",
      "text_face_channelall",
      "text_face_channel",
      "text_face_channels_",
      "face_message_border",
      "text_face_system",
      "text_face_chat",
      "face_message_shineframe"
    ],
    "interactive": true,
    "inherits": [
      "MessageFace",
      "FaceSprite",
      "Sprite"
    ]
  },
  "OtherPlayerFace": {
    "key": "otherplayerface",
    "title": "OtherPlayerFace",
    "cls": "OtherPlayerFace",
    "parent": "FaceHandler",
    "pkg": "face.otherplayer",
    "file": "deobfuscated/face/otherplayer/OtherPlayerFace.as",
    "sys": "表情/头像（face）系统 —— 他人角色头像浮层（含右键操作菜单）",
    "desc": "他人角色头像浮层：仅保留头像/等级/名字（移除 HP/MP/EXP/SP 条），点击弹出操作菜单（查看/宠物/观战/加友/私聊/强制PK/组队/扔物品/称号/关闭），\n各菜单项向服务器发送对应协议。",
    "size": {
      "w": 148,
      "h": 83
    },
    "bg": "face_portrait_bg",
    "texts": 0,
    "resources": [
      "face_portrait_bg",
      "face_force_pk"
    ],
    "interactive": true,
    "inherits": [
      "OtherPlayerFace",
      "FaceHandler",
      "FaceSprite",
      "Sprite"
    ]
  },
  "OwerAction": {
    "key": "oweraction",
    "title": "OwerAction",
    "cls": "OwerAction",
    "parent": "Sprite",
    "pkg": "face.actions",
    "file": "deobfuscated/face/actions/OwerAction.as",
    "sys": "右上角\"我的动作\"浮标(face.actions，农场/家园系统动作入口)",
    "desc": "表现\"我的动作\"浮标中的单个动作图标单元——加载头像图并维护两条倒计时(开启倒计时 time / 关闭倒计时 closeTime)，\n倒计时归零分别启用交互(已开启+红光)与触发关闭回调(closeFun)，文本背景随尺寸自适应重绘。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": false,
    "inherits": [
      "OwerAction",
      "Sprite"
    ]
  },
  "PetFace": {
    "key": "petface",
    "title": "PetFace",
    "cls": "PetFace",
    "parent": "FaceHandler",
    "pkg": "face",
    "file": "deobfuscated/face/PetFace.as",
    "sys": "表情/头像（face）系统 —— 宠物头像浮层",
    "desc": "宠物头像浮层（继承 FaceHandler）：宽高 148x73，默认用宠物默认头像，_type=RESUME_PET；重写 EXP/SP 条布局（宠物无 SP 条），\n并实现 HP/MP/EXP 文本与遮罩的具体绘制（按当前/最大值比例裁剪遮罩宽度）。",
    "size": {
      "w": 148,
      "h": 73
    },
    "bg": "face_portrait_bg",
    "texts": 0,
    "resources": [
      "face_portrait_bg"
    ],
    "interactive": false,
    "inherits": [
      "PetFace",
      "FaceHandler",
      "FaceSprite",
      "Sprite"
    ]
  },
  "PhoneFace": {
    "key": "phoneface",
    "title": "PhoneFace",
    "cls": "PhoneFace",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/PhoneFace.as",
    "sys": "表情/头像（face）系统 —— “手机绑定”奖励浮标",
    "desc": "手机绑定奖励浮标：播放 phoneBing.swf 特效图标，点击上报绑定(sendClient)，与 GiftFace 协调屏幕水平位置(setFaceXY)。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "PhoneFace",
      "Sprite"
    ]
  },
  "PlayerFace": {
    "key": "playerface",
    "title": "PlayerFace",
    "cls": "PlayerFace",
    "parent": "FaceHandler",
    "pkg": "face",
    "file": "deobfuscated/face/PlayerFace.as",
    "sys": "表情/头像（face）系统 —— 玩家自身头像浮层",
    "desc": "玩家自身头像浮层（继承 FaceHandler）：宽 148 高 83，贴右侧屏幕；_type=RESUME_PLAYER；\n实现 HP/MP/SP/EXP 四条状态条的具体文本与遮罩绘制（按当前/最大值比例裁剪遮罩宽度），\n并提供\"隐藏/显示套装\"切换条（点击向服务器发送 sendSuitShowMSG）。",
    "size": {
      "w": 148,
      "h": 83
    },
    "bg": "face_portrait_bg",
    "texts": 1,
    "resources": [
      "face_portrait_bg",
      "face_force_pk"
    ],
    "interactive": true,
    "inherits": [
      "PlayerFace",
      "FaceHandler",
      "FaceSprite",
      "Sprite"
    ]
  },
  "PromptClass": {
    "key": "promptclass",
    "title": "PromptClass",
    "cls": "PromptClass",
    "parent": "BottomPrompt",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/PromptClass.as",
    "sys": "底部提示(face.prompt)",
    "desc": "带可视背景的底部提示消息(继承 BottomPrompt 并满足 CurrentMessage 契约)。默认显示 6 秒。\n自身即显示对象(displayObject=this)，可在 set content 时通过 setChatText 渲染为聊天样式文本(宽 156)。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "PromptClass",
      "BottomPrompt"
    ]
  },
  "PromptClass02": {
    "key": "promptclass02",
    "title": "PromptClass02",
    "cls": "PromptClass02",
    "parent": "PromptClass03",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/PromptClass02.as",
    "sys": "底部提示(face.prompt)",
    "desc": "红色强调型提示消息(继承 PromptClass03)。构造时把正文包裹为红色字体(<font color='#FF0000'>)，\n默认显示时长 15 秒(较基类更长)，用于错误/警告/重要广播。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "PromptClass02",
      "PromptClass03"
    ]
  },
  "PromptClass03": {
    "key": "promptclass03",
    "title": "PromptClass03",
    "cls": "PromptClass03",
    "parent": "",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/PromptClass03.as",
    "sys": "底部提示(face.prompt)",
    "desc": "当前消息的基类实现(CurrentMessage)。持有内容(_content)、剩余时间(_restTime)与默认时长(_defaultTime)、是否贴底(_bottom)。\n提供通用的 getter/setter 与 renew(重置剩余时间为默认)。子类 CurrentMessage02/PromptClass02/04 仅调整默认时长与内容样式。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "PromptClass03"
    ]
  },
  "PromptClass04": {
    "key": "promptclass04",
    "title": "PromptClass04",
    "cls": "PromptClass04",
    "parent": "PromptClass03",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/PromptClass04.as",
    "sys": "底部提示(face.prompt)",
    "desc": "普通提示消息(继承 PromptClass03)。与基类默认时长一致，默认显示 10 秒，正文不附加颜色样式。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": false,
    "inherits": [
      "PromptClass04",
      "PromptClass03"
    ]
  },
  "PromptFace": {
    "key": "promptface",
    "title": "PromptFace",
    "cls": "PromptFace",
    "parent": "Sprite",
    "pkg": "face",
    "file": "deobfuscated/face/PromptFace.as",
    "sys": "提示系统(face) —— 屏幕各类悬浮提示/气泡的总管",
    "desc": "汇总并管理所有屏幕提示浮层：顶部滚动消息(topPrompt)、大喇叭(_buglePrompt)、底部系统提示(_bottomPrompt)、\n跟随鼠标的信息提示(infoPrompt)、装备对比提示(contrastList)、当前发言气泡(_privateChatPrompt/_chatPromptArray)、\n自动挂机图标(autoFountImg)、战斗教学提示(_battleTutorPrompt/1)、当前线提示(_nowLinePrompt)，并驱动聊天气泡计时收起。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [
      "state_autofount"
    ],
    "interactive": true,
    "inherits": [
      "PromptFace",
      "Sprite"
    ]
  },
  "PromptProgress": {
    "key": "promptprogress",
    "title": "PromptProgress",
    "cls": "PromptProgress",
    "parent": "SendPanel",
    "pkg": "face",
    "file": "deobfuscated/face/PromptProgress.as",
    "sys": "采集/生活技能进度提示(face)",
    "desc": "屏幕上的采集(生活技能)进度面板。显示\"采集中/等待\"标题，进度条按服务器节拍刷新百分比，点击可取消；\n进度条悬停时弹出采集提示(infoPrompt)。复用 SendPanel 的基础进度条与面板结构。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "PromptProgress",
      "SendPanel"
    ]
  },
  "RaceFace": {
    "key": "raceface",
    "title": "RaceFace",
    "cls": "RaceFace",
    "parent": "Sprite",
    "pkg": "face.match",
    "file": "deobfuscated/face/match/RaceFace.as",
    "sys": "赛事/匹配浮层(face.match)",
    "desc": "赛事报名/排队等待浮标——显示自由赛排队人数或公会赛 1 秒倒计时，提供\"离开排队\"按钮，支持拖拽与点击空白处寻路移动玩家。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [
      "panel_btn_bg1",
      "text_panel_exit_race_freedom",
      "text_panel_exit_race_guild"
    ],
    "interactive": true,
    "inherits": [
      "RaceFace",
      "Sprite"
    ]
  },
  "RaidFace": {
    "key": "raidface",
    "title": "RaidFace",
    "cls": "RaidFace",
    "parent": "FaceSprite02",
    "pkg": "face",
    "file": "deobfuscated/face/RaidFace.as",
    "sys": "突袭/Raid 战况浮层(face)",
    "desc": "显示世界突袭(Raid)活动进度浮标：列出待击败列表(fallowList)与当前进行列表(curList)中各目标描述、剩余时间与状态\n(待战/已击败/已编成/计时中/暂停)。每拍由 timeHandler 重算刷新；可拖拽(继承 FaceSprite02)。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": false,
    "inherits": [
      "RaidFace",
      "FaceSprite02",
      "Sprite"
    ]
  },
  "SendMessageFace": {
    "key": "sendmessageface",
    "title": "SendMessageFace",
    "cls": "SendMessageFace",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/SendMessageFace.as",
    "sys": "聊天输入栏(face)",
    "desc": "屏幕左下角聊天/发言输入浮层。承载输入框(chatInput，限 80 字)、表情/活动/清屏/回答/频道/颜色/侧栏开关等按钮，\n处理快捷键唤起面板、发送消息(sendChatMsg，支持\"/\"指令与链接转换)、私聊提示、侧栏收展动画(toggleSideBar)。",
    "size": {
      "w": 205,
      "h": 50
    },
    "bg": "face_message_chat",
    "texts": 1,
    "resources": [
      "face_message_chat",
      "face_channel_bg2",
      "text_face_emote",
      "text_face_active",
      "text_face_clear_text",
      "text_face_answer",
      "text_face_channels_2",
      "face_Switch",
      "text_face_channels_"
    ],
    "interactive": true,
    "inherits": [
      "SendMessageFace",
      "FaceSprite",
      "Sprite"
    ]
  },
  "ShortCutFace": {
    "key": "shortcutface",
    "title": "ShortCutFace",
    "cls": "ShortCutFace",
    "parent": "FaceSprite",
    "pkg": "face.shortcut",
    "file": "deobfuscated/face/shortcut/ShortCutFace.as",
    "sys": "快捷键栏(face.shortcut)",
    "desc": "屏幕底部(426,510)的快捷键栏。共 20 个格子分\"玩家(curType=0)/宠物(curType=1)\"两组各 10 格，可切换(switchHandler)。\n每格由 ShortCutParent 承载(物品/技能图标、数量、可用置灰)；提供显示/隐藏开关(flag)、锁定(isLock)、掩膜(isMask)、选中边框、\n性能档切换(switchPerformance)。实现 ParentPanel 供 ShortCutParent 接入 itemLayer。",
    "size": null,
    "bg": "face_player_cut_lock",
    "texts": 1,
    "resources": [
      "face_player_cut_lock",
      "face_Switch",
      "face_player_cut_unlock",
      "face_PlayerShortCut",
      "face_petShortCut",
      "face_pet_cut_lock",
      "face_pet_cut_unlock",
      "item_select"
    ],
    "interactive": true,
    "inherits": [
      "ShortCutFace",
      "FaceSprite",
      "Sprite"
    ]
  },
  "ShortCutParent": {
    "key": "shortcutparent",
    "title": "ShortCutParent",
    "cls": "ShortCutParent",
    "parent": "Sprite",
    "pkg": "face.shortcut",
    "file": "deobfuscated/face/shortcut/ShortCutParent.as",
    "sys": "快捷键栏(face.shortcut)，作为 ShortCutFace 中单个格子的承载组件",
    "desc": "承载一个快捷键(物品/技能)格子的图标(imgSprite)、数量(countField)、可用性置灰(canuse)、描述(desc)与提示(getInfo)。\n通过 parentPanel(ParentPanel 契约，实际为 ShortCutFace 或 AutoBattleItemPanel)挂载到图标层 itemLayer。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": true,
    "inherits": [
      "ShortCutParent",
      "Sprite"
    ]
  },
  "ShowplayerButton": {
    "key": "showplayerbutton",
    "title": "ShowplayerButton",
    "cls": "ShowplayerButton",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/ShowplayerButton.as",
    "sys": "浮层按钮(face)",
    "desc": "通用\"图标按钮\"浮层单元：用一张图片(_image)作背景，可指定尺寸/位置、是否参与互斥锁(_isForLock)、是否可换图(isChangeFace)。\n默认在 y=46-高度 处贴底显示；也可按 setY 用 initBackground 在指定坐标绘制。flag4=false 时置灰(disabled 态)。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "ShowplayerButton",
      "FaceSprite",
      "Sprite"
    ]
  },
  "SideBarFace": {
    "key": "sidebarface",
    "title": "SideBarFace",
    "cls": "SideBarFace",
    "parent": "FaceSprite",
    "pkg": "face",
    "file": "deobfuscated/face/SideBarFace.as",
    "sys": "右侧工具栏(face)",
    "desc": "屏幕右侧竖条工具条(SideBar)：绘制圆角画布(50x520)，放置一个\"下载快捷方式\"按钮(buttonList)。\n按钮点击打开官网攻略页并(登录态)上报 sendDownloadShortcut。可被 SendMessageFace.toggleSideBar 收展(showFace/clearFace)。",
    "size": null,
    "bg": "face_side_bg",
    "texts": 0,
    "resources": [
      "face_side_bg",
      "face_download_shortcut"
    ],
    "interactive": false,
    "inherits": [
      "SideBarFace",
      "FaceSprite",
      "Sprite"
    ]
  },
  "StepTaskCompleteHint": {
    "key": "steptaskcompletehint",
    "title": "StepTaskCompleteHint",
    "cls": "StepTaskCompleteHint",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepTaskCompleteHint.as",
    "sys": "新手引导—任务完成提示步(face.tutor)",
    "desc": "引导步\"任务完成提示\"：聚焦引导 NPC(_tutorNpcId=1004)，绘制镂空高亮、放置模拟鼠标、在 NPC 头顶显示提示文案，\n并监听对话面板打开(TUTOR_TALKPANEL_OPEN)以推进到\"任务完成展示(StepTaskCompleteShow)\"步。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepTaskCompleteHint"
    ]
  },
  "StepTaskCompleteShow": {
    "key": "steptaskcompleteshow",
    "title": "StepTaskCompleteShow",
    "cls": "StepTaskCompleteShow",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepTaskCompleteShow.as",
    "sys": "新手引导—任务完成展示步(face.tutor)",
    "desc": "引导步\"任务完成展示\"：在固定坐标(564,265)放置模拟鼠标、在(410,267,156,16)绘制镂空高亮、在(564,330)显示提示文案，\n并监听对话面板关闭(TUTOR_TALKPANEL_CLOSE)以推进到\"任务完成提交(StepTaskCompleteSubmit)\"步。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepTaskCompleteShow"
    ]
  },
  "StepTaskCompleteSubmit": {
    "key": "steptaskcompletesubmit",
    "title": "StepTaskCompleteSubmit",
    "cls": "StepTaskCompleteSubmit",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepTaskCompleteSubmit.as",
    "sys": "新手引导—任务完成提交步(face.tutor)",
    "desc": "引导步\"任务完成提交\"：在(445,430)放置模拟鼠标、在(361,428,82,26)绘制镂空高亮(提交按钮区)、在(445,490)显示提示文案，\n并监听对话面板关闭(TUTOR_TALKPANEL_CLOSE)以推进到末步\"最后欢迎(StepWelcomeLast)\"。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepTaskCompleteSubmit"
    ]
  },
  "StepWelcome": {
    "key": "stepwelcome",
    "title": "StepWelcome",
    "cls": "StepWelcome",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepWelcome.as",
    "sys": "新手引导—欢迎首步(face.tutor)",
    "desc": "引导流程第一步：展示欢迎提示框(faceTutorPrompt)，在确认按钮上方放置模拟鼠标，绘制全屏半透明遮罩(0.8，\n聚焦确认按钮)，上报引导步(\"welcome\")；监听确认后切到\"欢迎→引导(WELCOME_TO_TUTOR)\"步。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepWelcome"
    ]
  },
  "StepWelcomeLast": {
    "key": "stepwelcomelast",
    "title": "StepWelcomeLast",
    "cls": "StepWelcomeLast",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepWelcomeLast.as",
    "sys": "新手引导—欢迎末步(face.tutor)",
    "desc": "引导流程最后一步：展示末步提示框(STEP_WELCOME_LAST)，在确认按钮上方放置模拟鼠标，绘制全屏半透明遮罩(0.8)，\n上报引导步(\"welcomeLast\")；确认后直接终止整个新手引导(tutorManager.stopTutor)，不再切换下一步。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepWelcomeLast"
    ]
  },
  "StepWelcomeTaskAccept": {
    "key": "stepwelcometaskaccept",
    "title": "StepWelcomeTaskAccept",
    "cls": "StepWelcomeTaskAccept",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepWelcomeTaskAccept.as",
    "sys": "新手引导—提交欢迎任务步(face.tutor)",
    "desc": "引导步\"提交欢迎任务\"：在任务提交按钮区(390,446,80,26)绘制镂空高亮、在(470,446)放模拟鼠标、在(470,510)显示提示(STEP_WELCOME_TASK_ACCEPT)，\n并监听对话面板关闭(TUTOR_TALKPANEL_CLOSE)以推进到\"任务完成提示(TASK_COMPLETE_HINT)\"步。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepWelcomeTaskAccept"
    ]
  },
  "StepWelcomeTaskShow": {
    "key": "stepwelcometaskshow",
    "title": "StepWelcomeTaskShow",
    "cls": "StepWelcomeTaskShow",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepWelcomeTaskShow.as",
    "sys": "新手引导—展示欢迎任务步(face.tutor)",
    "desc": "引导步\"展示欢迎任务\"：在(530,240)放模拟鼠标、任务条目区(410,240,114,18)绘制镂空高亮、在(530,300)显示提示(STEP_WELCOME_TAKS_SHOW)，\n并监听对话面板关闭(TUTOR_TALKPANEL_CLOSE)以推进到\"提交欢迎任务(ACCEPT_WELCOME_TASK_SUBMIT)\"步。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepWelcomeTaskShow"
    ]
  },
  "StepWelcomeToTutor": {
    "key": "stepwelcometotutor",
    "title": "StepWelcomeToTutor",
    "cls": "StepWelcomeToTutor",
    "parent": "",
    "pkg": "face.tutor",
    "file": "deobfuscated/face/tutor/StepWelcomeToTutor.as",
    "sys": "新手引导—欢迎→引导过渡步(face.tutor)",
    "desc": "引导流程\"欢迎→引导\"过渡步：把镜头/玩家移动到引导 NPC(_tutorNpcId=1004，不触发对话)，上报引导步(\"welcomToTutor\")；\n待地图与玩家资源加载完成(onComplete)后，在 NPC 处一次性展示镂空高亮/模拟鼠标/提示；对话面板打开时切到\"展示欢迎任务\"步。",
    "size": null,
    "bg": "",
    "texts": 0,
    "resources": [],
    "interactive": true,
    "inherits": [
      "StepWelcomeToTutor"
    ]
  },
  "TaskFace": {
    "key": "taskface",
    "title": "TaskFace",
    "cls": "TaskFace",
    "parent": "FaceSprite02",
    "pkg": "face",
    "file": "deobfuscated/face/TaskFace.as",
    "sys": "任务追踪浮层(face)",
    "desc": "屏幕左侧任务追踪列表(可拖拽，继承 FaceSprite02)。维护\"关注任务\"列表(taskFollowlist，最多 4 条)，\n每条约 350ms 重绘：显示标题(未完成橙/已完成紫)、剩余时间(有 times 时启动计时)、条件条目。点击任务可寻路/打开任务面板。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": true,
    "inherits": [
      "TaskFace",
      "FaceSprite02",
      "Sprite"
    ]
  },
  "TopPrompt": {
    "key": "topprompt",
    "title": "TopPrompt",
    "cls": "TopPrompt",
    "parent": "BottomPrompt",
    "pkg": "face.prompt",
    "file": "deobfuscated/face/prompt/TopPrompt.as",
    "sys": "顶部消息滚动提示(face.prompt)",
    "desc": "顶部居中滚动广播/系统消息条。维护\"处理中列表(messageProcessList,最多3条)\"与\"缓冲列表(messageBufferList)\"，\n每 1 秒(messageTimer)递减各消息剩余时间、移除超时、在有空位时把缓冲广播补入并刷新显示。\n支持文本超链接点击(寻路/查看)、鼠标移动联动场景光标。",
    "size": null,
    "bg": "",
    "texts": 1,
    "resources": [],
    "interactive": true,
    "inherits": [
      "TopPrompt",
      "BottomPrompt"
    ]
  }
};
export const FACE_BY_ROOT = {
  "action": "ActionFace",
  "addpoint": "AddpointFace",
  "battlelist": "BattleListFace",
  "battletutor": "BattleTutor",
  "bottom": "BottomFace",
  "buff": "BuffSprite",
  "buffsprite": "BuffSprite02",
  "bugleprompt": "BuglePrompt",
  "city": "CityFace",
  "cityname": "CityNameFace",
  "commoninfo": "CommonInfoFace",
  "currentmessage": "CurrentMessage02",
  "divtask": "DivTaskFace",
  "exitwatchbattle": "ExitWatchBattleFace",
  "face": "FaceHandler",
  "facesprite": "FaceSprite02",
  "facetutor": "FaceTutor",
  "facetutorprompt": "FaceTutorPrompt",
  "flowers": "FlowersFace",
  "gift": "GiftFace",
  "group": "GroupFace",
  "instance": "Instance",
  "message": "MessageFace",
  "otherplayer": "OtherPlayerFace",
  "oweraction": "OwerAction",
  "pet": "PetFace",
  "phone": "PhoneFace",
  "player": "PlayerFace",
  "promptclass": "PromptClass",
  "promptclass03": "PromptClass03",
  "promptclass04": "PromptClass04",
  "prompt": "PromptFace",
  "promptprogress": "PromptProgress",
  "race": "RaceFace",
  "raid": "RaidFace",
  "sendmessage": "SendMessageFace",
  "shortcut": "ShortCutFace",
  "shortcutparent": "ShortCutParent",
  "showplayer": "ShowplayerButton",
  "sidebar": "SideBarFace",
  "steptaskcompletehint": "StepTaskCompleteHint",
  "steptaskcompleteshow": "StepTaskCompleteShow",
  "steptaskcompletesubmit": "StepTaskCompleteSubmit",
  "stepwelcome": "StepWelcome",
  "stepwelcomelast": "StepWelcomeLast",
  "stepwelcometaskaccept": "StepWelcomeTaskAccept",
  "stepwelcometaskshow": "StepWelcomeTaskShow",
  "stepwelcometotutor": "StepWelcomeToTutor",
  "task": "TaskFace",
  "topprompt": "TopPrompt"
};
